social/urls.py
from django.contrib import admin
from django.urls import path
from signup import views as sview
from login import views as lview
from userprofile import views as uview
from urllib.parse import unquote

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lview.loginview,  name='login'),
    path('login/', lview.loginview,  name='login'),
    path('logout/', lview.logout,  name='logout'),
    path('signup/', sview.signupview, name='signup'),
    path('validate/', sview.validateview,  name='validate'),
    path('home/', uview.homeview,  name='home'),
    path('search/', uview.searchview,  name='search'),
    path('post/', uview.savepost,  name='post'),
    path('sendrequest/', uview.sendrequest,  name='sendrequest'),
    path('friendprofile/<id>/', uview.friendprofile,  name='friendprofile'),

    
]

signup/models.py
from django.db import models

# Create your models here.
class signupdata(models.Model):
    name=models.CharField(max_length=50)
    phone=models.BigIntegerField(unique=True)
    email=models.EmailField(max_length=50,unique=True)
    gender=models.CharField(max_length=5)
    active=models.CharField(default=False,max_length=7)
    password=models.CharField(max_length=10)
    otp=models.IntegerField(default=0)

signup/views.py
from django.shortcuts import render
from .form import signupform
from .models import signupdata as User
from django.http import HttpResponseRedirect,JsonResponse
from django.contrib import messages

def signupview(request):
    if request.session.get('userid','DEFAULT') =="DEFAULT":
        if request.method == 'POST':
            form = signupform(request.POST)
            if form.is_valid():
                userObj = form.cleaned_data
                username = userObj['name']
                email =  userObj['email']
                password =  userObj['password']
                gender=userObj['gender']
                phone=userObj['phone']
                reg=User(name=username,email=email, password=password,phone=phone,gender=gender)
                reg.save()
                messages.info(request, 'Account Created Sucessfully')
                return HttpResponseRedirect('/login/')
            else:
                return render(request, 'signup.html', {'form' : form})    
        else:
            form = signupform()
            return render(request, 'signup.html', {'form' : form})
    else:
        form = signupform()
        return render(request, 'signup.html', {'form' : form})

def validateview(request):
    if request.method=="POST":
        data,value=request.POST.items()
        if User.objects.filter(**{data[0]:data[1]}).exists():
            return JsonResponse({'status':0})
        else:
            return JsonResponse({'status':1})

signup/templates/signup.html
{% extends 'core.html' %}
{% load static %}
{% block main %}
<form class="form-group"  autocomplete="off" method="POST">
    {% csrf_token %} 
        <div class="container-fluid border bg-white w-75 h-75 mt-5" style="max-width:800px;" >
            <div class="row">
                <div class="col-12 text-white  text-center text-weight-bold py-2 bg-dark"><h1>SIGNUP</h1></div>
            </div>
            <div class="col-12  text-center pt-2 " id="msg" style="color: red;"></div>
            <div class="row mt-4">
                <div class="col-sm-12 col-lg-5 offset-lg-1 text-dark text-left mb-2 px-2 font-weight-bold">
                    {{form.name.label_tag}}
                    {{form.name}}
                </div>
                <div class="col-sm-12 col-lg-5  text-dark text-left mb-2 px-2 font-weight-bold">
                    {{form.email.label_tag}}
                    {{form.email}}
                </div>
                <div class="col-sm-12 col-lg-5 offset-lg-1 font-weight-bold text-dark text-left mb-2 px-2">
                    {{form.phone.label_tag}}
                    {{form.phone}}
                </div>
                <div class="col-sm-12 col-lg-5  text-dark text-left mb-2 font-weight-bold px-2">
                    {{form.gender.label_tag}}
                    {{form.gender}}
                </div>
                <div class="col-sm-12 col-lg-5 offset-lg-1 text-dark text-left mb-2 px-2 font-weight-bold">
                    {{form.password.label_tag}}
                    {{form.password}}
                </div>
                <div class="col-sm-12 col-lg-5  text-dark text-left mb-2 font-weight-bold px-2">
                    {{form.cpassword.label_tag}}
                    {{form.cpassword}}
                </div>
                <div class="col-12 mt-2 text-center">
                    {{form.accept}}
                    <a href="#" target="_blank">-Term and Condition</a>
                </div>
            <div class="w-100"></div>
            <div class="row mt-2" style="margin: auto;">
                <div class="col-6  text-right text-weight-bold my-2 pb-4 ">
                    <input type="submit" value="Submit" class="btn btn-primary" id="submit">
                </div>
                <div class="col-6 text-left text-weight-bold my-2 ">
                    <a href="{% url 'login' %}"  class="btn btn-primary">Login</a>
                </div>
            </div>
        </div> 
</form>
{% include 'validate.html' %}
{% endblock main %}

signup/templates/validate.html
<script>
    var count=0;
    function checkdata(key,value){
        csr=$("input[name=csrfmiddlewaretoken]").val();
        mydata={[key]:value,csrfmiddlewaretoken:csr}
        $.ajax({
                url: "{% url 'validate' %}",
                method: "POST",
                data: mydata,
                success: function(data){
                    checkstatus(key,data['status']);
                }
            });
    }
    function checkstatus(key,data){
        if(data==0){
            addcss('#id_'+key,key+' already used')
        }
        else{
            removecss('#id_'+key)
        }
    }
    function removecss(id){
        $(id).removeClass('warning')
        $('#msg').text('');
    }
    function addcss(id,msg){
        $(id).addClass('warning').val('');
        $('#msg').text(msg);
    }
    $(document).ready(function(){
        $('#id_email').blur(function(){
            var em=$(this).val();
            if(em.search('@gmail.com')!=-1){
                checkdata('email',em);
            }
            else{
                addcss('#id_email','Only gmail id')
            }
        });
        $('#id_phone').blur(function(){
            var ph=$(this).val();
            if(ph.length==10){
                checkdata('phone',ph);
            }
            else{
                addcss('#id_phone','Use valid 10 digit number')
            }
        });
        $('#id_password').blur(function(){
            var pass=$(this).val();
            if(pass.length<5){
                addcss('#id_password','Use valid password grater than 5')
            }
            else{
                removecss('#id_password')
            }
        });
        $('#id_cpassword').blur(function(){
            var pass=$(this).val();
            if(pass!==$('#id_password').val()){
                addcss('#id_cpassword','Check password')
            }
            else{
                removecss('#id_cpassword')
            }
        });
    });
</script>